# Generated by Django 6.0.4 on 2026-04-17 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_delete_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_vector', models.JSONField(help_text='Stores the 768-D feature vector from Hugging Face API')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='core.basepetreport')),
            ],
        ),
    ]
