# Generated by Django 6.0.4 on 2026-04-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embedding',
            name='feature_vector',
            field=models.JSONField(),
        ),
    ]
