# Generated by Django 6.0.4 on 2026-04-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_adoptionpost_base_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('CLAIM_APPROVED', 'Ownership Verified'), ('NEW_SIGHTING', 'New Sighting Alert'), ('FUND_ACTIVE', 'Medical Fund Approved'), ('RESCUE_CONFIRMED', 'Rescue Verified'), ('DONATION_REVIEW', 'Review Donation'), ('DONATION_SUCCESS', 'Donation Received')], default='FUND_ACTIVE', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='related_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
