# Generated by Django 6.0.4 on 2026-04-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification_notif_type_notification_related_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationlog',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=20),
        ),
    ]
