# Generated by Django 6.0.4 on 2026-04-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_donationlog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionpost',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unknown', 'Unknown')], max_length=20),
        ),
        migrations.AlterField(
            model_name='basepetreport',
            name='primary_color',
            field=models.CharField(choices=[('Black', 'Black'), ('White', 'White'), ('Brown', 'Brown'), ('Gray', 'Gray'), ('Golden', 'Golden'), ('Ginger', 'Ginger'), ('Calico', 'Calico'), ('Mixed', 'Mixed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='basepetreport',
            name='species',
            field=models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Bird', 'Bird'), ('Rabbit', 'Rabbit'), ('Reptile', 'Reptile'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='donationlog',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='lostreport',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Unknown', 'Unknown')], max_length=20),
        ),
        migrations.AlterField(
            model_name='medicalfundrequest',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='ownershipclaim',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='reporttimeline',
            name='event_type',
            field=models.CharField(choices=[('Reported', 'Reported'), ('Sighting', 'Sighting'), ('Update', 'Update'), ('Rescue', 'Rescue'), ('Fundraiser', 'Fundraiser'), ('Reunited', 'Reunited')], max_length=100),
        ),
        migrations.AlterField(
            model_name='rescueverification',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='sightingreport',
            name='condition',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Injured', 'Injured'), ('Deceased', 'Deceased')], max_length=100),
        ),
    ]
