# Generated by Django 6.0.4 on 2026-04-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_adoptionpost_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basepetreport',
            name='location',
            field=models.CharField(choices=[('Dhanmondi', 'Dhanmondi'), ('Gulshan 1', 'Gulshan 1'), ('Gulshan 2', 'Gulshan 2'), ('Banani', 'Banani'), ('Uttara', 'Uttara'), ('Mirpur 1', 'Mirpur 1'), ('Mirpur 10', 'Mirpur 10'), ('Mirpur 12', 'Mirpur 12'), ('Mohammadpur', 'Mohammadpur'), ('Bashundhara R/A', 'Bashundhara R/A'), ('Farmgate', 'Farmgate'), ('Tejgaon', 'Tejgaon'), ('Malibagh', 'Malibagh'), ('Banasree', 'Banasree'), ('Lalmatia', 'Lalmatia'), ('Baridhara', 'Baridhara'), ('Nikunja', 'Nikunja'), ('Khilgaon', 'Khilgaon'), ('Badda', 'Badda'), ('Puran Dhaka', 'Puran Dhaka')], max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, choices=[('Dhanmondi', 'Dhanmondi'), ('Gulshan 1', 'Gulshan 1'), ('Gulshan 2', 'Gulshan 2'), ('Banani', 'Banani'), ('Uttara', 'Uttara'), ('Mirpur 1', 'Mirpur 1'), ('Mirpur 10', 'Mirpur 10'), ('Mirpur 12', 'Mirpur 12'), ('Mohammadpur', 'Mohammadpur'), ('Bashundhara R/A', 'Bashundhara R/A'), ('Farmgate', 'Farmgate'), ('Tejgaon', 'Tejgaon'), ('Malibagh', 'Malibagh'), ('Banasree', 'Banasree'), ('Lalmatia', 'Lalmatia'), ('Baridhara', 'Baridhara'), ('Nikunja', 'Nikunja'), ('Khilgaon', 'Khilgaon'), ('Badda', 'Badda'), ('Puran Dhaka', 'Puran Dhaka')], max_length=255, null=True),
        ),
    ]
