# Generated by Django 6.0.4 on 2026-04-17 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_basepetreport_location_alter_profile_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Embedding',
        ),
    ]
