# Generated by Django 6.0.4 on 2026-04-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownershipclaim',
            name='claim_type',
            field=models.CharField(choices=[('Manual', 'Manual'), ('ML Match', 'ML Match')], default='Manual', max_length=50),
        ),
    ]
