# Generated by Django 6.0.4 on 2026-04-17 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_ownershipclaim_claim_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('CLAIM_APPROVED', 'Ownership Verified'), ('NEW_SIGHTING', 'New Sighting Alert'), ('FUND_ACTIVE', 'Medical Fund Approved'), ('RESCUE_CONFIRMED', 'Rescue Verified'), ('RESCUE_REJECTED', 'Rescue Proof Rejected'), ('DONATION_REVIEW', 'Review Donation'), ('DONATION_SUCCESS', 'Donation Received'), ('CLAIM_REJECTED', 'Ownership Claim Rejected')], max_length=20),
        ),
    ]
